idf_component_register(
    SRCS
        "main.c"
        "config.c"
        "led_control.c"
        "buzzer.c"
        "motion_sensor.c"
        "button.c"
        "effects.c"
        "state_machine.c"
        "wifi_web.c"
        "battery.c"
        "ldr.c"
        "adc1_shared.c"
    INCLUDE_DIRS
        "."
        "../include"
    REQUIRES
        nvs_flash
        driver
        esp_wifi
        esp_http_server
        esp_netif
        esp_event
        esp_timer
        freertos
        json
        esp_adc
        app_update
        esp_partition
        esp_app_format
)
